function dba_42aa = room_default_dba(soundcard_in_channels, soundcard_mic_port, mic_type, fs, barometer_correction)

        mic_route = zeros(soundcard_in_channels, 1);
        mic_route(soundcard_mic_port, 1) = 1.0;
        room_noise_floor = soundcard_api_record(mic_route, 30, fs);
        
        % load the latest calibrator recordings: 42AA and 42AB
        [latest_42aa, dt_42aa] = latest_timestamp('Data/Calibration/42AA');
        [latest_42ab, dt_42ab] = latest_timestamp('Data/Calibration/42AB');
        disp('Use latest calibration files:')
        disp(latest_42aa);
        disp(latest_42ab);
        
        % time assurance for valid calibration of reference mic
        dt_now = datetime();
        if hours(dt_now - dt_42aa) > 24
            error('Over 24 hours passed since last calibration of the reference mic, please re-claibrate with 42AA! Abort.')
        elseif hours(dt_now - dt_42ab) > 24
            error('Over 24 hours passed since last calibration of the reference mic, please re-claibrate with 42AB! Abort.')
        else
            disp('Both latest reference mic calibrations are done within 24 hours, ok to proceed...')
        end
        
        
        % spl (no weighting) shall give similar values for cross validation:
        % termiate the measurement if difference > 0.5
        dbspl_42aa = sound_pressure_level(['Data/Calibration/42AA/',latest_42aa,'/cal-250hz-114dB(105.4dBA)_',mic_type,'_12AA(0dB)_UFX.wav'], ...
            room_noise_floor, ...
            room_noise_floor, ...
            1, ...
            0, ...
            0, ...
            100, ...
            12000, ...
            114+barometer_correction, ...
            48000, ...
            16384, ...
            16384/4, ...
            ' ');
        dbspl_42ab = sound_pressure_level(['Data/Calibration/42AB/',latest_42ab,'/cal-1khz-114dB_',mic_type,'_12AA(0dB)_UFX.wav'], ...
            room_noise_floor, ...
            room_noise_floor, ...
            1, ...
            0, ...
            0, ...
            100, ...
            12000, ...
            114, ...
            48000, ...
            16384, ...
            16384/4, ...
            ' ');
        if abs(dbspl_42aa - dbspl_42ab) > 0.5
            error('calibration deviation > 0.5 dB(A), please re-calibrate! Abort');
        else
            disp('calibration deviation: dB');
            disp(abs(dbspl_42aa - dbspl_42ab));
        end
        
        % if cross validation ok, use 42AA for dBA measurement
        dba_42aa = sound_pressure_level(['Data/Calibration/42AA/',latest_42aa,'/cal-250hz-114dB(105.4dBA)_',mic_type,'_12AA(0dB)_UFX.wav'], ...
            room_noise_floor, ...
            room_noise_floor, ...
            1, ...
            0, ...
            0, ...
            100, ...
            12000, ...
            105.4, ...
            48000, ...
            16384, ...
            16384/4, ...
            'a-weight');
        disp('dBA of room noise floor:');
        disp(dba_42aa);
        if dba_42aa > 30
            error('room is too noisy for automatic measurement? abort.');
        end

end