function spl_db = sound_pressure_level(calib_wav, ...
                                       measure_record, ...
                                       symbol, ...
                                       repeat, ...
                                       symbol_start, ...
                                       symbol_stop, ...
                                       frequency_low, ...
                                       frequency_high, ...
                                       calibrator_spl_db, ...
                                       sample_rate, ...
                                       frame_size, ...
                                       hop_size, ...
                                       weighting)

    [calib_record,fs] = audioread(calib_wav);
    assert(fs == sample_rate);
    %[measure_record,fs] = audioread(measure_wav);
    %assert(fs == sample_rate);
    %[symbol,fs] = audioread(symbol_wav);
    %assert(fs == sample_rate);
    
    if strcmp(weighting, 'a-weight')
        calib_record = filterA(calib_record, sample_rate);
        measure_record = filterA(measure_record, sample_rate);
        symbol = filterA(symbol, sample_rate);
    end
    
    spl_db = db20uPa(calib_record, measure_record, symbol, repeat, ...
                     symbol_start, symbol_stop, frequency_low, frequency_high, ...
                     calibrator_spl_db, sample_rate, frame_size, hop_size);
end